name: latexmk
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  latexmk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/latexmk-action@0.11.1
        with:
          cmd: make
          depends: DEPENDS.txt
      - uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: package
          clean: false
        if: github.ref == 'refs/heads/master'
